### ISSUE TITLE
Basic認証の認証情報について

### ISSUE THREAD

**Issue by dcash872** [cfm-system-team/hazard_alert#12]
「recipient/search」は、デフォルトでBasic認証になっておりますが、認証情報（ユーザID・パスワード）についてどこを参照すればよいかをお教え願えないでしょうか？現在は、客先デモのため、Basic認証の設定を一時的にOFFにしております。

**Comment by cfm-system-team** [comment]
デフォルト設定では、Usersテーブルに登録されているユーザ情報で認証することができます。   
本システムにはユーザ登録機能は実装されておりませんが、Laravelのtinkerを利用すると、簡単にユーザ登録できます。   
以下、tinkerを利用した例となります。   
この例で作成したユーザでベーシック認証する場合、ユーザ名は「test@sample.ne.jp」、パスワードが「password」となります。   
```bash
# プロジェクト直下で実行
$ php artisan tinker
Psy Shell v0.10.4 (PHP 7.4.7 — cli) by Justin Hileman
>>>App\User::create(['name' => 'sample', 'email' => 'test@sample.ne.jp', 'password' => bcrypt('password')]);
=> App\User {
     name: "sample",
     email: "test@sample.ne.jp",
     updated_at: "2020-06-25 14:00:00",
     created_at: "2020-06-25 14:00:00",
     id: 1,
   }
```

**Comment by dcash872** [comment]
ありがとうございます。上記の方法で試したいと思います。
結果については、後程ご連絡いたします。

**Comment by dcash872** [comment]
ご回答いただいた内容で、Basic認証が通りました。
大変ありがとうございました。

**Comment by cfm-system-team** [comment]
無事に認証できて何よりです。   
それでは本issueは解決したということで、クローズさせていただきます。
