### ISSUE TITLE
groupsテーブルに検索用に例えばcategoryという名のstring型のカラムを追加したい

### ISSUE THREAD

**Issue by kaosf** [cfm-system-team/hazard_alert#16]
DBへの変更があります．この変更は，PRを出したとして受け入れられる可能性はありますでしょうか？

今は私のforkしたリポジトリに案として置いてあるだけの状態です．

https://github.com/kaosf/hazard_alert/tree/add-category-to-groups

**Comment by cfm-system-team** [comment]
PRしていただけることは、大変ありがたいことですので、些細なことでも検討させていただきたいと考えております。   
ただ、DBの変更となりますと、システム全体に影響が及びますので、ご提案いただく内容によっては、本システムに取り込むのが難しい場合もございます。   
その点はご容赦いただけますと幸いですが、いずれにしましても、PRがあれば必ず検討はさせていただきます。

**Comment by kaosf** [comment]
ご回答ありがとうございます🙏

ですよね

DBの変更が必要なカスタマイズの要望がうちの方でありましてあんまりそれもやりすぎると本家と乖離するから上手くupstreamと共存出来るようにカスタマイズすることを考えないといけないなぁという思いもありまず先に確認させて頂きたかった次第でございます

**Comment by cfm-system-team** [comment]
本システムにコントリビュートしていただけることは大変ありがたいですが、まずは各々の環境において最適な形で本システムをご活用いただくことを優先にお考えいただければと存じます。   
その上で、修正や改善が必要な箇所であったり、汎用的に扱えそうな機能などがあればPRしていただく流れのほうが、ご負担が減るのではないかと存じますので、ご一考くだされば幸いです。

**Comment by cfm-system-team** [comment]
こちら、一度クローズさせていただきます。
