### ISSUE TITLE
利用者がメールアドレスを登録する画面へ移動できない

### ISSUE THREAD

**Issue by dcash872** [cfm-system-team/hazard_alert#18]
お世話になっております。
先日は、ベーシック認証の件のご質問に回答いただきありがとうございました。

また1点、ご質問がございます。
表題の件ですが、/groups/register にて各イベント会場などが発行したQRコードを元に
利用者としてメールアドレス登録画面を開こうとすると、「正常に接続できませんでした」
となり、移動することができません。

QRコード読込時のURLとしては、
「https://www.risk-notice.spark.jp/recipient/register/xxxxx.....」（xxxx....：GETパラメータの暗号化文字列）
ですので、「Repicient」コントローラの「register」メソッドの処理を確認しましたが、何か仕様上見落としている
点がございますでしょうか？

ご教授をよろしくお願いいたします。

**Comment by cfm-system-team** [comment]
お世話になっております。   
まず、下記の2点について確認させていただければ存じます。   
```
・アクセス時の端末は、スマートフォンか、あるいは「ガラケー」と呼ばれているフィーチャーフォンか   
・アクセス時にロードバランサを経由しているか   
```
以上、ご確認の程よろしくお願いいたします。

**Comment by dcash872** [comment]
ご連絡いただきありがとうございます。
>・アクセス時の端末は、スマートフォンか、あるいは「ガラケー」と呼ばれているフィーチャーフォンか？
⇒ アクセス時の端末は「スマートフォン/PC」になります。

>・アクセス時にロードバランサを経由しているか 
⇒ ロードバランサは私用しておりません。

以上となります。
よろしくお願いいたします。

**Comment by cfm-system-team** [comment]
ご確認ありがとうございます。  
構築されている環境がこちらでは把握しかねますので、推測でしかありませんが、QRコード読み取り時のサーバ側のリダイレクト処理に何か問題が発生しているのではないかと考えられます。  
QRコード生成処理をそのままお使いになられている場合、ガラケー対応のため、http://～ のURLで発行されるようになっており、スマートフォンやPC環境でアクセスした際は、「Repicient」コントローラで必ずhttps経由でのアクセスになるようにリダイレクトされるようになっています。   
このとき、サーバ側の設定でhttpでのアクセスを拒否していたりすると、エラーとなってしまいます。  
今一度、リダイレクト処理まわりをご確認いただくと良いかもしれません。

**Comment by dcash872** [comment]
ご回答いただきありがとうございました。
社内で再度確認いたします。
動作確認ができ次第、ご連絡いたします。

**Comment by cfm-system-team** [comment]
その後、状況はいかがでしょうか。   
もし問題が解決しているようでしたら、本issueはクローズしたいと考えております。

**Comment by cfm-system-team** [comment]
本件、解決されたとのご報告はありませんが、一旦クローズさせていただきます。  
もしまだ解決されていない場合は、お手数ですが本issueをreopen、または新規にissueを作成してください。
