### ISSUE TITLE
PDF

### ISSUE THREAD

**Issue by dcash872** [cfm-system-team/hazard_alert#22]

**Comment by dcash872** [comment]
表題の件ですが、現在PDFファイルの背景に独自の画像を埋め込もうとしているのですが、
スタイルの部分で以下のように記述しても、ファイルが読み込めていないため、どのように設定すればよいかをご教授願えませんでしょうか？
なお、以下のファイルパスは「resources」は以下に「img」フォルダを置いているイメージです。
また、試しに直接imgタグでアクセスかけても、ファイルが壊れているように見えました。

[/views/group/pop_pdf.blade.php]
`body {
 　 font-family: ipag !important;
      background-image: url('../../img/画像ファイル名');
 }`

`<img src="../../img/画像ファイル名">`

**Comment by cfm-system-team** [comment]
view上で画像を読み込みたい場合、resourcesフォルダではなくpublicフォルダに画像を格納していただくと、問題なく読み込めるようになると思いますので、一度ご確認いただければと存じます。

**Comment by dcash872** [comment]
お世話になっております。ご返信ありがとうございました。
たったいま試したところ、添付ファイルのような状態になっております。
なお、コードは上記とほぼ同様です。

`body {font-family: ipag !important; background-image: url('../../../public/img/画像ファイル名'); }`

ファイルが参照できていない状態だと思いますが、これの修正方法がありましたら、お教え願えないでしょうか？
よろしくお願いいたします。
![コメント 2020-08-03 110848](https://user-images.githubusercontent.com/11435762/89139475-ba34c100-d579-11ea-8177-119291f20734.png)

**Comment by cfm-system-team** [comment]
下記のような構造になっている場合、相対パスは「img/sample.png」となります。  
こちらを参考に、もう一度パスのご確認いただければと存じます。  
```
--public
  --img
     --sample.png
```

**Comment by dcash872** [comment]
ありがとうございます。
<p>タグの中に<img>タグを入れた場合は、画像が表示されました。
しかし、bodyタグの「background-image」として表示させようとしたところ、反映されないようです。
domPDFの仕様の影響でしょうか？

よろしくお願いいたします。

**Comment by cfm-system-team** [comment]
詳細にはまだ調査できていませんが、publicフォルダ直下の画像であれば、「background-image」として表示できるようです。

**Comment by dcash872** [comment]
時間の関係上、imgタグとCSSスタイリングで何とか解決することができました。
この件については、別途こちらでも調べてみたいと思います。
一旦、本件をクローズしていただけないでしょうか？

ご協力いただき、大変ありがとうございました。

**Comment by cfm-system-team** [comment]
承知いたしました。  
それでは一旦クローズさせていただきます。
