### ISSUE TITLE
DATETIME 型カラムに紐づく Eloquent モデルプロパティのデータ型を Carbon で扱えるようにしたい

### ISSUE THREAD

**Issue by KeisukeKudo** [cfm-system-team/hazard_alert#4]
タイトルの通り､改善提案です｡

例えばこちら

https://github.com/cfm-system-team/hazard_alert/blob/master/database/migrations/2020_05_21_041432_add_address_to_groups_table.php#L19-L20

https://github.com/cfm-system-team/hazard_alert/blob/master/app/Http/Controllers/RecipientController.php#L48-L49

データベース上 `start_at` や `end_at` は `DATETIME` と定義していますが､ Elquent では `string` として取得されてしまいます｡
`Model` クラスにて､ `$casts` または `$dates` に対象カラム名を設定することで､ `Carbon` オブジェクトとして取得できます｡

https://readouble.com/laravel/7.x/ja/eloquent-mutators.html

こちら､変更することに問題はないでしょうか?
なにか不都合があればご指摘いただきたいです｡

**Comment by cfm-system-team** [comment]
改善のご提案、ありがとうございます。
データ型の変更ですが、特段不都合はございません。
どうぞ、よろしくお願いいたします。
